Main page of portfolio
BEKMAL/Portfolio pull request #1
Opened 2022-05-26 13:40 UTC by BEKMAL

the main page of the portfolio

2022-05-26 16:08 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @BEKMAL,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-26 16:08 UTC, omar-muhamad commented on README.md
> +
- [x] Kindly put the project name which is `Portfolio` like you did before and removed it.to make your README file look professional.
- [x] Please add a proper description like `This project is the first time to make my personal portfolio with microvese using .......`

2022-05-26 16:08 UTC, omar-muhamad commented on README.md
> +[Live Demo Link](https://livedemo.com)
- [x] Please remove this section because now you don't have a live demo link to your project you will add it later to make your README file look professional.

2022-05-26 16:08 UTC, omar-muhamad commented on README.md
> +- LinkedIn: [Bekalu-malede](https://linkedin.com/in/linkedinhandle)
- [x] Please put your actual social links instead of `https://github.com/githubhandle`, `https://twitter.com/twitterhandle`, and `https://linkedin.com/in/linkedinhandle` to make your README file look professional.

2022-05-26 16:08 UTC, omar-muhamad commented on index.html
> +         <a href="#"><i class="material-icons-outlined"> menu </i></a>
- [x] Please add your hamburger icon in a `<button>` tag instead of an `<a>` tag because in the following projects you will implement mobile menu to it.

2022-05-26 16:08 UTC, omar-muhamad commented on index.html
> +          </div>
- [x] Please add this main text to a `<h1>` tag instead of `<p>` tag and remove the wrapping `<div>` tag for semantic reasons.

2022-05-26 16:08 UTC, omar-muhamad commented on index.html
> +          </div>
- [ ] Please remove this wrapping `<div>` tag to your text and don't overuse `<div>` tag unless you need them to contain more than one element for styling purposes that's for semantic reasons.

2022-05-26 16:08 UTC, omar-muhamad commented on index.html
> +          </div>
- [ ] Same here Please remove this wrapping `<div>` tag.

2022-05-26 16:08 UTC, omar-muhamad commented on index.html
> +          </div>
- [x] Please remove this wrapping `<div>` tag.
- [x] and Kindly wrap your icon with an `<a>` and add your social links to it because when you click on any icon it is supposed to take you to your social profile for this site.
[Hint] for example you can do it like that:
` <li><a href="your social profile link"><i class="fa fa-facebook fa-2x"></i></a></li>`

2022-05-26 16:08 UTC, omar-muhamad commented on styles.css
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&display=swap");
- [x] I can see that you imported the font family used in the Figma design but you didn't use it in your design, So Please add the correct font family to each element of your header and headline section and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/170525589-d8920851-2162-4fa5-a2ee-0e038dbbe5d5.png)  | ![image](https://user-images.githubusercontent.com/68796232/170525370-5a45baa8-5f71-407f-bc08-f373a8499dbf.png)  |

2022-05-26 16:08 UTC, omar-muhamad commented on styles.css
> +  background-image: url("background.png");
- [ ] Please add this background image to the headline section only not for the whole `<main>` tag that contains the header and headline section to match the given design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/170526265-075986e1-35b6-47d9-902d-1f976c1d1be2.png)  | ![image](https://user-images.githubusercontent.com/68796232/170526491-9a1af195-3270-4d74-8fec-2eb86a971db7.png)  |

2022-05-26 16:08 UTC, Omar-Muhamad commented on styles.css
> +}
- [ ] Please add the correct margin-top value to your header by decreasing it to match the given design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/170527163-7c59d671-3006-440e-9758-6b0642e628d7.png)  | ![image](https://user-images.githubusercontent.com/68796232/170527276-e02572ea-2aba-496d-be38-98b51726c09c.png) |

2022-05-26 16:08 UTC, Omar-Muhamad commented on styles.css
> +  color: #acb7c3;
- [ ] For `lets connect` please add the correct margin-left value to match the given Figma design.
- [ ] For the social icons Kindly make them smaller a little bit and add the correct color to them and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/170528083-77669655-77d9-487d-87b7-d1a28030c88c.png)  | ![image](https://user-images.githubusercontent.com/68796232/170528112-967aaece-5581-43c9-913a-131bcaf9a5fa.png)  |

2022-05-26 18:57 UTC, BEKMAL commented on styles.css
> +  background-image: url("background.png");
thank you for you comment but i prefer this one

2022-05-26 19:17 UTC, muneebulrehman commented on index.html
> +          </div>
Please follow up with this suggestion. `div `and `<p>` are both block level elements, so you don't need to envelop a single `p` tag within a `div` tag.

2022-05-26 19:17 UTC, muneebulrehman commented on styles.css
> +  background-image: url("background.png");
The top space still persists, please fix it as suggested by the previous reviewer.

2022-05-26 19:17 UTC, muneebulrehman commented on index.html
> +            <a href="#" class="connect">LET'S CONNECT</a>
Please remove the wrapping `<div>` as suggested by the previous reviewer.

2022-05-26 19:17 UTC, muneebulrehman commented on styles.css
> +  background-image: url("background.png");
Please, try to stick to the design template you have chosen, and any comment which is not labeled with Optional is mandatory and needs to be changed. Please implement the changes requested by the previous reviewer.

2022-05-26 19:25 UTC, muneebulrehman requested changes
Hi @BEKMAL , 

Great work on making some of the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Linters are passing
- Good documentation.

 ## Required Changes ♻️
_Check the comments under the review._

**Any comment which is not labeled as **_Optional_** by the reviewer is mandatory and needs to be fixed before submitting for a rereview. A code reviewer has more experience and will only recommend changes that will help you grow as a programmer and enhance the quality of code you write. Please keep this in mind.**
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 09:33 UTC, m05e5 approved these changes
# Hi @BEKMAL , 

### Status: Approved ✔️
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


:+1: You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete! 
Congratulations! 🎉 


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 09:45 UTC, merged